import Modal from "@/components/Modal";
import "./globals.css";

export const metadata = {
  title: "Trello-2.0",
  description: "Generated by Itay Mizrachi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Modal />
      </body>
    </html>
  );
}
